/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Delivery;

import java.awt.*;
import java.sql.SQLException;
import java.util.*;
import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class Delivery extends javax.swing.JPanel {

	/**
	 * Creates new form Delivery
	 */
	public Delivery() {

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable_DeliveryList = new javax.swing.JTable();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable_NewProduct = new javax.swing.JTable();
		checkbox_marker_alla = new java.awt.Checkbox();
		jButton_Ok = new javax.swing.JButton();
		jButton_New_product = new javax.swing.JButton();
		jLabel_Delivery = new javax.swing.JLabel();



		jTable_DeliveryList.setAutoCreateRowSorter(true);
		jTable_DeliveryList.setModel(new javax.swing.table.DefaultTableModel(
				deliveredTable,
				new String [] {
						"ID", "Name", "Ref Nr", "Price", "Type", "Unit", "Amount", "Confirmed"
				}
				) {
			Class[] types = new Class [] {
					java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class

			};



			public Class getColumnClass(int columnIndex) {
				return types [columnIndex];
			}
		});
		jTable_DeliveryList.getModel().addTableModelListener(new TableModelListener() {

			public void tableChanged(TableModelEvent e) {
				int row = e.getFirstRow();
				int column = e.getColumn();
				TableModel model = (TableModel)e.getSource();
				deliveredTable[row][column] = model.getValueAt(row, column);
				temp = deliveredTable[row][column];
				String str = temp.toString(); 
				d = Double.valueOf(str).doubleValue();
				System.out.println(d);
				deliveredTable[row][column] = d;


			}
		});

		jTable_DeliveryList.setColumnSelectionAllowed(true);
		jTable_DeliveryList.setEditingColumn(0);
		jTable_DeliveryList.setEditingRow(0);
		jTable_DeliveryList.setRowHeight(20);
		jTable_DeliveryList.setSelectionBackground(new java.awt.Color(235, 235, 235));
		jScrollPane1.setViewportView(jTable_DeliveryList);
		jTable_DeliveryList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

		jTable_NewProduct.setAutoCreateRowSorter(true);
		jTable_NewProduct.setModel(new javax.swing.table.DefaultTableModel(
				newProductTable,
				new String [] {
						"ID", "Name", "Ref Nr", "Price", "Type", "Unit", "Amount"
				}
				));
		jTable_NewProduct.setColumnSelectionAllowed(true);
		jTable_NewProduct.setEditingColumn(0);
		jTable_NewProduct.setEditingRow(0);
		jTable_NewProduct.setRowHeight(20);
		jScrollPane5.setViewportView(jTable_NewProduct);
		jTable_NewProduct.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

		checkbox_marker_alla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		checkbox_marker_alla.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		checkbox_marker_alla.setLabel("Mark All");
		checkbox_marker_alla.addComponentListener(new java.awt.event.ComponentAdapter() {
			public void componentMoved(java.awt.event.ComponentEvent evt) {
				checkbox_marker_allaComponentMoved(evt);
			}
		});

		jButton_Ok.setText("Ok");
		jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_OkActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButton_New_product.setText("New product");
		jButton_New_product.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_New_productActionPerformed(evt);
			}
		});

		jLabel_Delivery.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel_Delivery.setText("Delivery");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jButton_New_product)
								.addComponent(jButton_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel_Delivery)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(checkbox_marker_alla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(checkbox_marker_alla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_Delivery))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton_Ok)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton_New_product)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
	}// </editor-fold>

	private void checkbox_marker_allaComponentMoved(java.awt.event.ComponentEvent evt) {                                                    
		// TODO add your handling code here:
	} 



	private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                           

		if(evt.getSource() == jButton_Ok)
		{
			addID.clear();
			addAmount.clear();
			{	
				for(int i = 0; i< deliveredTable.length; i++)
				{	
					
					Object id = deliveredTable[i][0];
					addID.add(id);
					double amount = (Double) deliveredTable[i][6];
					addAmount.add(amount);
					Delivered delivered = new Delivered();
					delivered.addAmount(addID, addAmount);
					
				}
				System.out.println(addID);
				System.out.println(addAmount);
			}
		}
	}                                          

	private void jButton_New_productActionPerformed(java.awt.event.ActionEvent evt) {                                                    
		// TODO add your handling code here:
	}                                                   

	// Variables declaration - do not modify
	private java.awt.Checkbox checkbox_marker_alla;
	private javax.swing.JButton jButton_New_product;
	private javax.swing.JButton jButton_Ok;
	private javax.swing.JLabel jLabel_Delivery;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTable jTable_NewProduct;
	private javax.swing.JTable jTable_DeliveryList;
	double double1 = 5.00f;
	private Object [][] deliveredTable =  {{12, "strawberry marmelade", 8, 10, "Dry", "Liter", 0.0},
			                                {5, "toblerone", 7, 20, "Dry", "Kg", 0.0}};
	private Object [][] newProductTable = null;
	public ArrayList<Object> addID = new ArrayList<Object>();
	public ArrayList<Object> addAmount = new ArrayList<Object>();
	Object temp;
	double d;
	// End of variables declaration
}
