/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Order;

import gui.MainMenu;

import java.awt.Panel;
import java.util.ArrayList;

import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

import Searches.Search_Fun;
import Searches.Search_Gui;
import Searches.Searcher;

/**
 * 
 * @author DELL
 */
public class Order_gui extends javax.swing.JPanel {

	Object[][] table = null;

	Object[][] table_Search = null;

	int rowCount = 0;
	int columnCount = 0;
	Object id = 0;
	int j = 0;

	public Order_gui(Object[][] x) throws Exception {
		initComponents(x);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(Object[][] x) throws Exception {

		jButton_Ok = new javax.swing.JButton();
		jButton_Add = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable_SearchResult = new javax.swing.JTable();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable_Order = new javax.swing.JTable();
		jLabel_Order_Products = new javax.swing.JLabel();
		jTextField_Order_Search = new javax.swing.JTextField();
		jButton_Order_Search = new javax.swing.JButton();
		jButton_Delete = new javax.swing.JButton();

		// printOrder rc = new printOrder();
		// table = rc.PrintOrder();
		// rowCount = table.length;
		// rowCount++;
		// System.out.println(rowCount);
		// table = new Object[rowCount][7];

		printOrder po = new printOrder();
		table = po.PrintOrder();
		table_Search = x;

		while (id != null) {
			id = table[rowCount][columnCount];
			rowCount++;

		}

		jButton_Order_Search.setText("Search");
		jButton_Order_Search
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton_Order_SearchActionPerformed(evt);
					}
				});
		jButton_Ok.setText("Ok");
		jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_OkActionPerformed(evt);
			}
		});

		jButton_Add.setText("Add to order");
		jButton_Add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_AddActionPerformed(evt);
			}
		});

		jTable_SearchResult.setAutoCreateRowSorter(true);
		jTable_SearchResult.setModel(new javax.swing.table.DefaultTableModel(
				table_Search, new String[] { "ID", "Name", "Ref Nr", "Price",
						"Type", "Unit", "Amount", "Select" }) {
			Class[] types = new Class[] { java.lang.Object.class,
					java.lang.Object.class, java.lang.Object.class,
					java.lang.Object.class, java.lang.Object.class,
					java.lang.Object.class, java.lang.Object.class,
					java.lang.Boolean.class };
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false, true };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable_SearchResult.getModel().addTableModelListener(
				new TableModelListener() {

					public void tableChanged(TableModelEvent e) {
						System.out.println(e);
						int row = e.getFirstRow();
						int column = e.getColumn();
						TableModel model = (TableModel) e.getSource();
						String columnName = model.getColumnName(column);

						while (j < 8) {

							table[rowCount][j] = model.getValueAt(row, j);
							j++;
						}

						;
					}
				});
		jTable_SearchResult.setColumnSelectionAllowed(true);
		jTable_SearchResult.setEditingColumn(0);
		jTable_SearchResult.setEditingRow(0);
		jTable_SearchResult.setRowHeight(20);
		jScrollPane3.setViewportView(jTable_SearchResult);
		jTable_SearchResult
				.getColumnModel()
				.getSelectionModel()
				.setSelectionMode(
						javax.swing.ListSelectionModel.SINGLE_SELECTION);

		jTable_Order.setAutoCreateRowSorter(true);
		jTable_Order.setBackground(new java.awt.Color(255, 255, 255));
		jTable_Order.setModel(new javax.swing.table.DefaultTableModel(table,
				new String[] { "ID", "Name", "Ref Nr", "Price", "Type", "Unit",
						"Amount" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable_Order.setEditingColumn(0);
		jTable_Order.setEditingRow(0);
		jTable_Order.setRowHeight(20);
		jScrollPane1.setViewportView(jTable_Order);
		jTable_Order.getColumnModel().getColumn(5).setResizable(false);
		jTable_Order.getColumnModel().getColumn(6).setResizable(false);

		jLabel_Order_Products.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel_Order_Products.setText("Order Products");

		jButton_Delete.setText("Delete");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jTextField_Order_Search,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										95,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButton_Order_Search)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jButton_Add))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jButton_Delete)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jButton_Ok,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										69,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(0,
																										0,
																										Short.MAX_VALUE)
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										544,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addComponent(
																		jLabel_Order_Products))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		jScrollPane3,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		544,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel_Order_Products)
								.addGap(1, 1, 1)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										201,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton_Ok)
												.addComponent(jButton_Delete))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										95,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton_Add)
												.addComponent(
														jTextField_Order_Search,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jButton_Order_Search))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_OkActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton_OkActionPerformed

	private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {

		rowCount++;
		j=0;
		jTable_Order.setModel(new javax.swing.table.DefaultTableModel(table,
				new String[] { "ID", "Name", "Ref Nr", "Price", "Type", "Unit",
						"Amount" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});

		// try {
		// MainMenu.Panel.removeAll();
		// Order_gui o = new Order_gui(null);
		// MainMenu.Panel.add(o);
		// MainMenu.Panel.setVisible(true);
		// o.setVisible(true);
		// this.invalidate();
		// this.validate();
		// } catch (Exception e) {
		// e.printStackTrace();
		// }
		//
	}

	private void jButton_Order_SearchActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_AddActionPerformed
		if (evt.getSource() == jButton_Order_Search) {

			String searchWord = jTextField_Order_Search.getText();
			Search_Order search_fun2 = new Search_Order();
			Searcher searcher2 = new Searcher();
			try {

				search_fun2.select();
			} catch (Exception e) {

				e.printStackTrace();
			}

			ArrayList<String> temp2 = searcher2.searchThrough(
					search_fun2.groceryList, searchWord);
			Object[][] guiTable2 = null;
			try {
				table_Search = search_fun2.combine(temp2);
				jTable_SearchResult.setAutoCreateRowSorter(true);
				jTable_SearchResult
						.setModel(new javax.swing.table.DefaultTableModel(
								table_Search, new String[] { "ID", "Name",
										"Ref Nr", "Price", "Type", "Unit",
										"Amount", "Select" }) {
							Class[] types = new Class[] {
									java.lang.Object.class,
									java.lang.Object.class,
									java.lang.Object.class,
									java.lang.Object.class,
									java.lang.Object.class,
									java.lang.Object.class,
									java.lang.Object.class,
									java.lang.Boolean.class };
							boolean[] canEdit = new boolean[] { false, false,
									false, false, false, false, false, true };

							public Class getColumnClass(int columnIndex) {
								return types[columnIndex];
							}

							public boolean isCellEditable(int rowIndex,
									int columnIndex) {
								return canEdit[columnIndex];
							}
						});
				jTable_SearchResult.getModel().addTableModelListener(
						new TableModelListener() {

							public void tableChanged(TableModelEvent e) {
								System.out.println(e);
								int row = e.getFirstRow();
								int column = e.getColumn();
								TableModel model = (TableModel) e.getSource();
								String columnName = model.getColumnName(column);

								while (j < 8) {

									table[rowCount - 1][j] = model.getValueAt(
											row, j);
									j++;
								}

								;
							}
						});
				// Order_gui s = new Order_gui(guiTable2);'
				// MainMenu.Panel.removeAll();
				// MainMenu.Panel.add(s);
				// MainMenu.Panel.setVisible(true);
				// s.setVisible(true);
				// MainMenu.Panel.invalidate();
				// MainMenu.Panel.validate();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}// GEN-LAST:event_jButton_AddActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_Add;
	private javax.swing.JButton jButton_Ok;
	private javax.swing.JButton jButton_Order_Search;
	private javax.swing.JButton jButton_Delete;
	private javax.swing.JLabel jLabel_Order_Products;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable_SearchResult;
	private javax.swing.JTable jTable_Order;
	private javax.swing.JTextField jTextField_Order_Search;
	// End of variables declaration//GEN-END:variables
}
