/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Order;

import gui.MainMenu;

import java.awt.Panel;
import java.util.ArrayList;

import Searches.Search_Fun;
import Searches.Search_Gui;
import Searches.Searcher;

/**
 *
 * @author DELL
 */
public class Order_gui extends javax.swing.JPanel {

	Object[][] table = null;

	Object[][] table_Search = null;

	
    public Order_gui(Object [][] x)throws Exception {
        initComponents(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Object [][] x)throws Exception {

        jButton_Ok = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Add = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Order = new javax.swing.JTable();
        jLabel_Order_Products = new javax.swing.JLabel();
        jTextField_Order_Search = new javax.swing.JTextField();
        jButton_Order_Search = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        
        printOrder po = new printOrder();
		table = po.PrintOrder();
		table_Search = x;
		
		jButton_Order_Search.setText("Search");
		jButton_Order_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButton_Order_SearchActionPerformed(evt);
            }
        });
        jButton_Ok.setText("Ok");
        jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkActionPerformed(evt);
            }
        });

        jButton_Add.setText("Add to order");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jTable_Add.setAutoCreateRowSorter(true);
        jTable_Add.setBackground(new java.awt.Color(255, 204, 204));
        jTable_Add.setModel(new javax.swing.table.DefaultTableModel(
        		table_Search,
            new String [] {
                "ID", "Name", "Ref Nr", "Price", "Type", "Unit", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Add.setEditingColumn(0);
        jTable_Add.setEditingRow(0);
        jTable_Add.setRowHeight(20);
        jScrollPane3.setViewportView(jTable_Add);

        jTable_Order.setAutoCreateRowSorter(true);
        jTable_Order.setBackground(new java.awt.Color(255, 204, 204));
        jTable_Order.setModel(new javax.swing.table.DefaultTableModel(
            table,
            new String [] {
                "ID", "Name", "Ref Nr", "Price", "Type", "Unit", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Order.setEditingColumn(0);
        jTable_Order.setEditingRow(0);
        jTable_Order.setRowHeight(20);
        jScrollPane1.setViewportView(jTable_Order);
        jTable_Order.getColumnModel().getColumn(5).setResizable(false);
        jTable_Order.getColumnModel().getColumn(6).setResizable(false);

        jLabel_Order_Products.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Order_Products.setText("Order Products");

        jButton_Delete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextField_Order_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Order_Search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Add))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel_Order_Products))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Order_Products)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Ok)
                    .addComponent(jButton_Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add)
                    .addComponent(jTextField_Order_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Order_Search))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OkActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_Order_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
    	if (evt.getSource() == jButton_Order_Search )
		{

			String searchWord = jTextField_Order_Search.getText();
			Search_Fun search_fun2 = new Search_Fun();
			Searcher searcher2 = new Searcher();
			try {

				search_fun2.select();
			} catch (Exception e) {

				e.printStackTrace();
			}

			ArrayList <String> temp2 = searcher2.searchThrough(search_fun2.groceryList, searchWord);
			Object [][] guiTable2 = null;
			try 
			{
				guiTable2 = search_fun2.combine(temp2);
				Order_gui s = new Order_gui(guiTable2);
				MainMenu.Panel.removeAll();
				MainMenu.Panel.add(s);
				MainMenu.Panel.setVisible(true);
				s.setVisible(true);
				MainMenu.Panel.invalidate();
				MainMenu.Panel.validate();
			} 
			catch (Exception e) 
			{ 
				e.printStackTrace();
			}
		}
    }//GEN-LAST:event_jButton_AddActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Ok;
    private javax.swing.JButton jButton_Order_Search;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JLabel jLabel_Order_Products;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Add;
    private javax.swing.JTable jTable_Order;
    private javax.swing.JTextField jTextField_Order_Search;
    // End of variables declaration//GEN-END:variables
}
